### ISSUE TITLE
Errors when CRLF is used instead of LF

### ISSUE THREAD

**Issue by weirdpattern** [j-f1/eslint-docs#7]
It seems the check is struggling with line breaks.
When I run `npm run docs:check` on Mac it works, but when I do the same on Windows I get errors.

![error](https://user-images.githubusercontent.com/19519411/31295734-4e87571c-aaa5-11e7-8113-ef3ff7db3325.png)

Not saying this is wrong, is detecting the changes just fine, but this will cause a lot of issues when committing from different OSes...

**Comment by j-f1** [comment]
Thanks for reporting this!

**Comment by j-f1** [comment]
Does running `npm i j-f1/eslint-docs#d9990d0` fix the issue for you?

**Comment by weirdpattern** [comment]
For some reason I cannot install from the commit or master (I tried both).
I cloned the repo and ran the tests, they all passed, so not sure if that would be good enough for you to push this to npm (my computer seem not to have any problems installing from npm).

I only tested on Windows... haven't had a chance to test on Mac

**Comment by j-f1** [comment]
@weirdpattern I’ve pushed the changes to `npm`. Can you test again?

**Comment by weirdpattern** [comment]
Getting this now...

![error](https://user-images.githubusercontent.com/19519411/31303788-100461cc-aad9-11e7-9d62-6d8c3f04faa3.png)

**Comment by weirdpattern** [comment]
I just tried on my Mac... same result...

**Comment by j-f1** [comment]
I think I’ve fixed that error. Can you try one more time?

**Comment by weirdpattern** [comment]
Sorry for the delay... working on both Windows and OSX  👍
